<a href="https://colab.research.google.com/github/muniprasadreddy/my-colab_work/blob/main/Image_Classification__1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###    Data:image


#  download manually the  image from goole
#   download dataset from kaggle.com
#   Build a image Web Crawler
#   use python libraries to scrape the images

In [ ]:
!pip install bing-image-downloader

In [ ]:
!mkdir images

mkdir: cannot create directory ‘images’: File exists


In [ ]:
from bing_image_downloader import downloader
downloader.download("fruits and vegetables",limit=50,output_dir='images'
,adult_filter_off=True)

[%] Downloading Images to /content/images/fruits and vegetables


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from https://kidsgardening.org/wp-content/uploads/2016/03/rainbow.png
[%] File Downloaded !

[%] Downloading Image #2 from https://static.fanpage.it/wp-content/uploads/sites/22/2018/07/istock-856749954.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://upload.wikimedia.org/wikipedia/commons/1/13/Fresh_cut_fruits_and_vegetables.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.todayifoundout.com/wp-content/uploads/2013/09/fruits-and-vegetables.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://4.bp.blogspot.com/-iCWLv2hDiXM/UM6yuDEIsQI/AAAAAAAAAHk/v2IFZwwqxUE/s1600/Fruits+and+Vegetables+(1).jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.ceceliahealth.com/wp-content/uploads/2021/02/iStock-924858812.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://www.lalpathlab

In [ ]:
from bing_image_downloader import downloader
downloader.download("ice cream",limit=50,output_dir='images'
,adult_filter_off=True)

[%] Downloading Images to /content/images/ice cream


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from http://smartcanucks.ca/wp-content/uploads/2012/08/ice_cream.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://cdn.theculturetrip.com/wp-content/uploads/2015/06/ice-cream2-pixabay.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://1.bp.blogspot.com/-9Rv6_tobzlI/TVTOEu0p8SI/AAAAAAAAAMc/7PLQQ5ZUcm0/s1600/Ice_Cream_dessert_02.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.tasteofhome.com/wp-content/uploads/2020/10/soft-serve-ice-cream-cone-1011538714.jpg?resize=1024
[%] File Downloaded !

[%] Downloading Image #5 from http://images6.fanpop.com/image/photos/33300000/ICE-CREAM-ice-cream-33393414-1366-768.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://2.bp.blogspot.com/-Bh9xohPIIrY/TprLZj2RV_I/AAAAAAAAEDo/edlD7EkrPjU/s1600/Ice+Cream.jpg
[%] File Downloaded !

[%] Downloading Image #7 from

In [ ]:
from bing_image_downloader import downloader
downloader.download("different pretty flowers",limit=50,output_dir='images'
,adult_filter_off=True)



[%] Downloading Images to /content/images/different pretty flowers


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from https://inspirationseek.com/wp-content/uploads/2014/05/Hibiscus-Beautiful-White-Flowers.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/60/88/b0/6088b05f2e83a253813fec734b11c26f.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/originals/d5/80/f0/d580f0bb5ebdf81b1675a557ab714a17.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/ab/76/9e/ab769ea246bd7d76d06f0a9e3389e121.png
[%] File Downloaded !

[%] Downloading Image #5 from https://jooinn.com/images/pretty-flowers-1.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://3.bp.blogspot.com/-Lki_dyMbGJM/WtRxaYEiNvI/AAAAAAAABi4/nCKIeEoxdiUac6dIJ1noyxvGIWvySIA9ACPcBGAYYCw/s1600/Tulips.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://media.cntraveler.com/phot

# preprocessing

In [ ]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize


In [ ]:


target = []
images = []
flat_data = []

Datadir = '/content/images'
Categories = ['different pretty flowers', 'fruits and vegetables', 'ice cream']

for cate in Categories:
    class_num = Categories.index(cate) ### Label encoding the values
    print(class_num)
    path = os.path.join(Datadir, cate)    # create path to use all the images
    print(path)


0
/content/images/different pretty flowers
1
/content/images/fruits and vegetables
2
/content/images/ice cream


In [ ]:
from skimage.io import imread
from skimage.transform import resize
import numpy as np

flat_data = []
images = []
target = []

for img in os.listdir(path):
    img_arry = imread(os.path.join(path, img))
    #print( img_arry.shape)
    #plt.imshow(img_arry)
                  ###### resize
### flatten
    img_resized = resize(img_arry, (200, 200, 3)) ## Normalized thr value from 0 to1
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)


flat_data = np.vstack(flat_data)
target = np.array(target)
images = np.array(images)


In [ ]:
flat_data[6]

array([0.88625648, 0.90980145, 0.89415881, ..., 0.81526615, 0.79167139,
       0.80743729])

In [ ]:
target

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
images

array([[[[0.00639652, 0.26125685, 0.6298843 ],
         [0.00730409, 0.26220239, 0.63083172],
         [0.00823216, 0.26309825, 0.63179972],
         ...,
         [0.00367081, 0.16935305, 0.49003671],
         [0.00150388, 0.16960953, 0.4802797 ],
         [0.00278558, 0.1689094 , 0.47951331]],

        [[0.00716779, 0.26196897, 0.63059727],
         [0.00838022, 0.26322258, 0.6319376 ],
         [0.00972059, 0.26459867, 0.63409022],
         ...,
         [0.00367148, 0.17014788, 0.48750154],
         [0.00150809, 0.16981924, 0.48004653],
         [0.00278703, 0.16891113, 0.47952572]],

        [[0.01000309, 0.26492912, 0.63356297],
         [0.01079345, 0.26617661, 0.63514897],
         [0.00920227, 0.26690564, 0.63749181],
         ...,
         [0.00374022, 0.17033019, 0.48696735],
         [0.0021162 , 0.17018595, 0.48095029],
         [0.00301265, 0.16912681, 0.48007224]],

        ...,

        [[0.99654119, 0.99630189, 0.99687599],
         [0.9965405 , 0.99630212, 0.99687599]

In [ ]:
len(flat_data[6])

120000

In [ ]:
200*200*3

120000

In [ ]:
target

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])